version: "3.1"
name: kurawa-league
services:
  db:
    image: postgis/postgis:15-3.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
